### ISSUE TITLE
Not finding PlotMe?

### ISSUE THREAD

**Issue by NeturonicAngelz** [boy0001/VoxelSniperRegions#2]
Doesn't seem to be recognizing PlotMe Anymore.

08.01 09:07:51 [Server] INFO fast-mode enabled for VoxelSniperRegions!
08.01 09:07:51 [Server] INFO Plugin 'PreciousStones' not found. PreciousStones features disabled.
08.01 09:07:51 [Server] INFO Plugin 'PlotSquared' not found. PlotSquared features disabled.
08.01 09:07:51 [Server] INFO Plugin 'GriefPrevention' not found. GriefPrevention features disabled.
08.01 09:07:51 [Server] INFO Plugin 'Residence' not found. Factions features disabled.
08.01 09:07:51 [Server] INFO Plugin 'Factions' not found. Factions features disabled.
08.01 09:07:51 [Server] INFO Plugin 'Towny' not found. Towny features disabled.
08.01 09:07:51 [Server] INFO Plugin 'PlotMe' not found. PlotMe features disabled.
08.01 09:07:51 [Server] INFO Plugin 'WorldGuard' found. Using it now.
08.01 09:07:51 [Server] INFO Running VS 5.170.0-SNAPSHOT-jnks317-gitfcb8fe1
08.01 09:07:51 [Server] INFO ======VoxelSniperRegions======
08.01 09:07:51 [Server] INFO Enabling VoxelSniperRegions v0.3.8

PlotMe Version:
0.15.2

VSR Version:
 v0.3.8

**Comment by MattBDev** [comment]
0.15.2 plotme does not work for voxelsniperreigions

**Comment by boy0001** [comment]
@MattBDev 
Is the API stable for the latest PlotMe?

**Comment by MattBDev** [comment]
@boy0001 The API is stable and there shouldn't be major changes without notice.

**Comment by boy0001** [comment]
http://dev.bukkit.org/bukkit-plugins/vsr/files/25-0-4-1/
