### ISSUE TITLE
VoxelSniperRegions Exception Problem

### ISSUE THREAD

**Issue by teledong** [boy0001/VoxelSniperRegions#6]
http://hastebin.com/uponaxigex.avrasm

Lastest version both plotsquared & VSR & Voxel......

Any Fix???

**Comment by boy0001** [comment]
https://www.dropbox.com/sh/lor5vc5z9idxuz5/AAAdiS08uoI4LQpPpuJbVrjga?dl=0

**Comment by teledong** [comment]
Problem Fixed.
